### ISSUE TITLE
For Helsinki event provide a form/document to suggest topics

### ISSUE THREAD

**Issue by bast** [NordicHPC/nordichpc.github.io#10]
It should be super low barrier. Already sending an email to a wide list can be too much and IMO a form or editing a document is less barrier.

Advantage (disadvantage?) of editing a document: you can see what others have suggested.

**Comment by rkdarst** [comment]
I made this:
  https://drive.google.com/drive/u/0/folders/1f6PwK_ihXoKRbQdyAQ2Kwh7z3h7UuxRh
It's under my institution google drive but is there a better place to put it?  Team drives would be good but dirs there can't be made "public to anyone with link".  How is the CodeRefinery google drive hosted?

**Comment by bast** [comment]
The drive is still under my personal account with access handed out individually to all team. I wish I could place it under something institutional instead.

**Comment by bast** [comment]
I think this is done?

**Comment by rkdarst** [comment]
Yes, good enough!
