### ISSUE TITLE
Rename "sysadmins"

### ISSUE THREAD

**Issue by bast** [NordicHPC/nordichpc.github.io#11]
In the big title to the left "Collaboration of Nordic HPC sysadmins" I am not sure about "sysadmins". I would rename to "Nordic HPC staff and friends" or something like that. I would not consider myself a sysadmin and many sysadmins are too far removed from users to be interested in such an event.

**Comment by rkdarst** [comment]
Very good, I was trying to think of a better way to present ourselves but I think that's it: "staff and friends".  What about even "computing facility staff and friends"?  Even a bit more general and makes sure to not be too HPC exclusive.  So now that there's a good idea, here's my proposal for how to present us:

We are for "computing facility staff and friends".  "Most of us are [either|somewhere between] application experts or sysadmins of clusters, those who are the front line of supporting research".  We have a "special focus on usability", a focus on "loose collaboration of development" and "networking within users and staff".

Would you say the above describes our essence properly?

**Comment by bast** [comment]
Yes I like it a lot!
