### ISSUE TITLE
For Helsinki event provide a public Google slide template for 3 solutions/problems

### ISSUE THREAD

**Issue by bast** [NordicHPC/nordichpc.github.io#9]
For the "Three cool things and three problems" provide a template where participants edit slides directly in a common public slideshow. Idea by @rkdarst

**Comment by bast** [comment]
In this slide deck it would be good if we create empty slides for all sites but if we show one or two for our sites already pre-filled so that participants see how we wanted this to look.

**Comment by bast** [comment]
I think this is done?

**Comment by rkdarst** [comment]
Yes - looks to be done.  I just typo-fixed my slides.
